### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by krutilin** [myflashlab/VolumePro-ANE#4]
Hi guys. 
I got this extension to handle hardware mute button. It works on iOS, but Android trows following stack into my face:

```
Failed to package AIR application MyApp.apk:
         dx tool failed:
         UNEXPECTED TOP-LEVEL EXCEPTION:
         java.lang.IllegalArgumentException: already added: Landroid/support/v4/graphics/drawable/DrawableWrapper;
         at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
         at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
         at com.android.dx.command.dexer.Main.processClass(Main.java:737)
         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
         at com.android.dx.command.dexer.Main.processOne(Main.java:637)
         at com.android.dx.command....
```

I also have following anes in my configuration:
```
        <extensionID>com.milkmangames.extensions.GAnalytics</extensionID>
        <extensionID>com.milkmangames.extensions.GoogleServices</extensionID>
```

But following configuration cause the exception on build:
```
        <extensionID>com.milkmangames.extensions.GAnalytics</extensionID>
        <extensionID>com.milkmangames.extensions.GoogleServices</extensionID>

        <extensionID>com.myflashlab.air.extensions.volume</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
```

**Comment by myflashlab** [comment]
This seems like a conflict between ANEs. Try removing the ```<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>``` and see how it goes.

**Comment by krutilin** [comment]
Well, app packaged without errors, after removing androidSupport ane. I will check app on set of the Android devices tomorrow to ensure that it works as expected.

**Comment by krutilin** [comment]
Looks like it works. Thanks.
